name: PullRequest

on:
  pull_request:
    branches:
    - v2.0-dev

jobs:
  MinQtDynamic:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        qt: [6.10.2]
        os: [ubuntu-24.04, macos-26, windows-2025]

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Install Python 3.10 version
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: ${{ matrix.os == 'macos-26' && 'arm64' || 'x64' }}
    - name: Install Qt (Linux|MacOS)
      if: (matrix.os == 'ubuntu-24.04') || (matrix.os == 'macos-26')
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt }}
        modules: qtshadertools
    - name: Install Qt (Windows)
      if: matrix.os == 'windows-2025'
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt }}
        arch: win64_msvc2022_64
        modules: qtshadertools
    - name: Configure and compile MNE-CPP
      run: |
        ./tools/build_project.bat all
    - name: Deploy binaries
      run: |
        ./tools/deploy.bat dynamic pack

  MaxQtDynamic:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        qt: [6.10.2]
        os: [ubuntu-24.04, macos-26, windows-2025]

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Install Python 3.10 version
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: ${{ matrix.os == 'macos-26' && 'arm64' || 'x64' }}
    - name: Install Qt (Linux|MacOS)
      if: (matrix.os == 'ubuntu-24.04') || (matrix.os == 'macos-26')
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt }}
        modules: qtshadertools
    - name: Install Qt (Windows)
      if: matrix.os == 'windows-2025'
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt }}
        arch: win64_msvc2022_64
        modules: qtshadertools
    - name: Configure and compile MNE-CPP
      run: |
        ./tools/build_project.bat all
    - name: Deploy binaries
      run: |
        ./tools/deploy.bat dynamic pack

#   QtStatic:
#     runs-on: ${{ matrix.os }}
# 
#     strategy:
#       fail-fast: false
#       max-parallel: 3
#       matrix:
#         os: [ubuntu-20.04, macos-11, windows-2019]
# 
#     steps:
#     - name: Clone repository
#       uses: actions/checkout@v3
#     - name: Install Python 3.7 version
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.7'
#         architecture: 'x64'
#     - name: Install OpenGL (Linux)
#       if: matrix.os == 'ubuntu-20.04'
#       run: |
#         sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
#         sudo apt-get update -q
#         sudo apt-get install build-essential libgl1-mesa-dev libicu55
#     - name: Install Qt (Linux)
#       if: matrix.os == 'ubuntu-20.04'
#       run: |
#         # Download the pre-built static version of Qt, which was created with the generateBinaries.yml workflow
#         wget -O qt5_5152_static_binaries_linux.tar.gz https://www.dropbox.com/s/tje7jp6tsn2dxdd/qt5_5152_static_binaries_linux.tar.gz?dl=0 
#         mkdir ../Qt5_binaries
#         tar xvzf qt5_5152_static_binaries_linux.tar.gz -C ../ -P
#     - name: Install Qt (MacOS)
#       if: matrix.os == 'macos-11'
#       run: |
#         # Download the pre-built static version of Qt, which was created with the generateBinaries.yml workflow
#         wget -O qt5_5152_static_binaries_macos.tar.gz https://www.dropbox.com/s/ccigarxk40wlxq0/qt5_5152_static_binaries_macos.tar.gz?dl=1
#         tar xvzf qt5_5152_static_binaries_macos.tar.gz -P
#     - name: Install Qt (Windows)
#       if: matrix.os == 'windows-2019'
#       run: |
#         # Download the pre-built static version of Qt, which was created with the generateBinaries.yml workflow
#         Invoke-WebRequest https://www.dropbox.com/s/47s49smjg499gnm/qt5_5152_static_binaries_win.zip?dl=1 -OutFile .\qt5_5152_static_binaries_win.zip
#         expand-archive -path "qt5_5152_static_binaries_win.zip" -destinationpath "..\"
#     - name: Configure and compile MNE-CPP (Linux|MacOS)
#       if: (matrix.os == 'ubuntu-20.04') || (matrix.os == 'macos-11')
#       run: |
#         export QT_DIR="$(pwd)/../Qt5_binaries/lib/cmake/Qt5"
#         export Qt5_DIR="$(pwd)/../Qt5_binaries/lib/cmake/Qt5"
#         ./tools/build_project.bat static all
#     - name: Configure and compile MNE-CPP (Windows)
#       if: matrix.os == 'windows-2019'
#       run: |
#         cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"
#         Get-Content "$env:temp\vcvars.txt" | Foreach-Object { if ($_ -match "^(.*?)=(.*)$") { Set-Content "env:\$($matches[1])" $matches[2] } }
#         $env:QT_DIR += "$PWD\..\Qt5_binaries\lib\cmake\Qt5"
#         $env:Qt5_DIR += "$PWD\..\Qt5_binaries\lib\cmake\Qt5"
#         ./tools/build_project.bat static all
#     - name: Deploy binaries
#       run: |
#         ./tools/deploy.bat static pack

  Tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-24.04, macos-26, windows-2025]

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Clone mne-cpp test data
      run: git clone https://github.com/mne-tools/mne-cpp-test-data.git resources/data/mne-cpp-test-data
    - name: Install Python 3.10 version
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: ${{ matrix.os == 'macos-26' && 'arm64' || 'x64' }}
    - name: Install Qt (Linux|MacOS)
      if: (matrix.os == 'ubuntu-24.04') || (matrix.os == 'macos-26')
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.10.2
        modules: qtshadertools
    - name: Install Qt (Windows)
      if: matrix.os == 'windows-2025'
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.10.2
        arch: win64_msvc2022_64
        modules: qtshadertools
    - name: Install MNE-Python
      run: |
        pip install --upgrade pip
        pip install mne numpy scipy
    - name: Cache MNE sample data
      id: cache-mne-data
      uses: actions/cache@v4
      with:
        path: ~/mne_data/MNE-sample-data
        key: mne-sample-data-v1
    - name: Download MNE sample data
      if: steps.cache-mne-data.outputs.cache-hit != 'true'
      run: |
        python -c "import mne; mne.datasets.sample.data_path()"
    - name: Configure and compile MNE-CPP (Linux)
      if: matrix.os == 'ubuntu-24.04'
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DWITH_CODE_COV=ON
        cmake --build build
    - name: Configure and compile MNE-CPP (MacOS)
      if: matrix.os == 'macos-26'
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
        cmake --build build
    - name: Configure and compile MNE-CPP (Windows)
      if: matrix.os == 'windows-2025'
      run: |
        # Setup VS compiler
        cmd.exe /c "call `"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"
        Get-Content "$env:temp\vcvars.txt" | Foreach-Object { if ($_ -match "^(.*?)=(.*)$") { Set-Content "env:\$($matches[1])" $matches[2] } }
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
        cmake --build build --config Release
    - name: Run tests (Linux)
      if: matrix.os == 'ubuntu-24.04'
      env:
        QTEST_FUNCTION_TIMEOUT: 900000
        QT_QPA_PLATFORM: offscreen
        MNE_DATA: ~/mne_data
      run: |
        ./tools/test_all.bat verbose withCoverage
    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-24.04'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Run tests (MacOS)
      if: matrix.os == 'macos-26'
      env:
        QTEST_FUNCTION_TIMEOUT: 900000
        QT_QPA_PLATFORM: offscreen
        MNE_DATA: ~/mne_data
      run: |
        ./tools/test_all.bat Release verbose
    - name: Run tests (Windows)
      if: matrix.os == 'windows-2025'
      env:
        QTEST_FUNCTION_TIMEOUT: 900000
        MNE_DATA: ~/mne_data
      run: |
        ./tools/test_all.bat Release verbose

  Doxygen:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Install Qt Dev Tools, Doxygen and Graphviz
      run: |
        sudo apt-get update -q
        sudo apt-get install -q qttools5-dev-tools doxygen graphviz
    - name: Run Doxygen and package result
      run: |
        cd doc/doxygen
        doxygen mne-cpp_doxyfile
